version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:uat-5.5
    ports:
      - "6464:443"
    volumes:
      - ./ohrm_dev:/var/www/html
      - ./config/php5/php.ini:/usr/local/etc/php/php.ini
      - ./config/mysql-client:/etc/mysql
      - ./config/apache2/sites-available:/etc/apache2/sites-available
      - ./config/apache2/cert:/etc/apache2/cert
      - ./logs/ubuntu_logs:/var/log/apache2
      - /etc/localtime:/etc/localtime
      - ./config/hostname:/etc/hostname
      - ./config/welcome:/etc/motd
      - ./config/ldap/nsswitch.conf:/etc/nsswitch.conf
      - ./config/ldap/ldap-nss.conf:/etc/libnss-ldap.conf
      - ./config/ldap/ldap-pam.conf:/etc/pam_ldap.conf
      - ./config/ldap/pam.d/common-auth:/etc/pam.d/common-auth
      - ./config/ldap/pam.d/common-account:/etc/pam.d/common-account
      - ./config/ldap/pam.d/common-password:/etc/pam.d/common-password
      - ./config/ldap/pam.d/common-session:/etc/pam.d/common-session
      - ./config/ldap/pam.d/common-session-noninteractive:/etc/pam.d/common-session-noninteractive
    links:
      - db
    restart: always
    container_name: uat_web

  db:
    image: mysql:5.5
    expose:
      - "3306"
    volumes:
      - ./config/mysql-server:/etc/mysql
      - ./logs/mysql_logs:/var/log
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    container_name: uat_mysql
